# Fluent Bit Parsers Configuration

[PARSER]
    Name   docker
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep On

[PARSER]
    Name   nginx
    Format regex
    Regex ^(?<remote_addr>[^ ]+) - (?<user>[^ ]+) \[(?<time>[^\]]+)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<status>[^ ]+) (?<body_bytes_sent>[^ ]+) "(?<http_referer>[^"]*)" "(?<user_agent>[^"]*)" "(?<xff>[^"]*)"$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Types status:integer body_bytes_sent:integer

[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%LZ
    Time_Keep On

[PARSER]
    Name   syslog
    Format regex
    Regex ^(?<time>[^ ]* [^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[^ ]*?)(?:\[(?<pid>[^ \]]*)\])?: (?<message>.*)$
    Time_Key time
    Time_Format %b %d %H:%M:%S
    Time_Keep Off
